### ISSUE TITLE
Week 1: Research, Environment Setup, and First Commit

### ISSUE THREAD

**Issue by adilanchian** [TeamMoodGitHub/Ab-Term-1#1]
I would like you to spend this week getting used to workflow of Github as well as getting used to your environment of React.js / Node.js setup. A few things I would like you to have accomplished this week are:

- [x] Pull down your repository from Github to start your local work
- [x] Create a branch off of master called `week-one`
- [x] Figure out a way to setup a "Hello World" project with React.js
- [ ] Start ramping up on CSS/React/HTML
- [x] Figure out how to get Node.js running on your machine
- [x] Create a simple Node.js server that you can launch locally
- [x] Come up with a skeleton for the design of your web app
- [x] Commit all your changes to your branch `week-one` and push that branch to remote
- [ ] Update and commit README as you see fit

Like always, make sure you utilize your resources! Within this Github organization alone there are many different options for help :)

Best of luck, I know you will kill it!

**Comment by adilanchian** [comment]
@SwapFunction - Curious, were you able to run your React app locally? If so could you tell me how you did it?

**Comment by adilanchian** [comment]
I created Week 2 issue for you sir! Take a look at it and answer this question for me when you get a chance 👍

**Comment by SwapFunction** [comment]
@adilanchian Yeah, I was able to run the react app locally. I did build the react app using npm run build. I did push the build folder containers earlier but I realized the code was more important so I pushed the code instead. It was run on localhost:5000 by default.

**Comment by adilanchian** [comment]
Forgot to close this, oops! Will close this issue now
