### ISSUE TITLE
Week 2: Fix up Github, Finalize design, Start implementing design

### ISSUE THREAD

**Issue by adilanchian** [TeamMoodGitHub/Ab-Term-1#4]
Hey Ab! So it seems like Github was giving you a bit of trouble last week. Don't worry about it! We are going to get it all figured out and right back on track. During this week I want you to focus on these things:

- [x] Create a new branch off of master called `week-two`
- [x] Start with a fresh hello world app for React.js that you can run locally (Hint: npm start)
- [ ] Once you have that running, go ahead and commit those changes to `week-two`
- [x] Finalize your design for your web app and add an image to your project
- [x] Start implementing your design

I think you should be able to get through this pretty quick. Let me know if you have any questions or concerns! Kick ass meng you got this :) Also please make sure to add and comments to this issue!

**Comment by adilanchian** [comment]
Ab,

Great work this week on the tasks at hand! Even though you got the tasks late AND you had stuff going on this past weekend, you still made it work. Awesome job :)

Im going to go ahead and close out this issue on the contingency that we roll over the unfinished task to week 3!

**Comment by SwapFunction** [comment]
Alright, I'll push the project overnight. You shall see it in a couple of hours hopefully !!

**Comment by adilanchian** [comment]
@SwapFunction Awesome man! Thanks for getting that done
