### ISSUE TITLE
Week 3: Backend Support, Dropdown UI, and API Research

### ISSUE THREAD

**Issue by adilanchian** [TeamMoodGitHub/Ab-Term-1#5]
W E E K 3 - Damn, we are getting close!

As per our standup call, I want you to work on a couple tasks this week. To reiterate again as well, I am laying out the general path that I believe you should take to keep going on this project. If you feel you may want to go a different route or do things differently, just let me know and we will realign the tasks! For this week I would like you to do the following:

- [x] Commit any changes you have made from last week to `week-two` branch and then MERGE that branch into `master` before starting on week three work. (Verify that your project runs from the master branch!)
- [x] Create a branch off of `master` called `week-three`
- [ ] Figure out a way to get your React project running on a Node.js server (Reach out to Bryan if you need any immediate help!)
- [ ] Create your dropdown navbar item with STATIC locations setup (this should help you get the navbar working before you start messing with APIs
- [ ] Finalize a color scheme for your project and apply it
- [ ] Do research on what APIs you will need in order to get your project running
- [ ] Commit all these changes to your branch named `week-three` (You can commit as many times as you want!)

After this week you will be nearly complete with the base of your project! Keep up the awesome work and don't forget to update this issue to keep track of your progress :)

**Comment by SwapFunction** [comment]
I was able to push and merge week-two into master branch, but it didn't include node_modules folder. So  that'll have to be installed in the hello-world folder in order for it to run, so create a new react app and just replace the other folders and files.

**Comment by adilanchian** [comment]
Awesome work this past week, Ab! Glad you are making progress. Even though it may seem slow, it doesn't matter. You are doing it! I will go ahead and add some unfinished tasks to your week 4 issue
