### ISSUE TITLE
Week 4: Running On Node, Dropdown menu, and UI/API setup

### ISSUE THREAD

**Issue by adilanchian** [TeamMoodGitHub/Ab-Term-1#8]
W E E K 4 - HALF WAY DONE LESSS GOOOO BOIIII

I am laying out the general path that I believe you should take to keep going on this project. If you feel you may want to go a different route or do things differently, just let me know and we will realign the tasks! For this week I would like you to do the following:

- [ ] Figure out a way to get your React project running on a Node.js server (Reach out to Bryan if you need any immediate help!)
- [x] Create your dropdown navbar item with STATIC locations setup (this should help you get the navbar working before you start messing with APIs
- [ ] Finalize a color scheme for your project and apply it
- [ ] Try out an API call to get real data for your site 
 
After this week your project should be really coming to life and almost in an MVP (most viable product) state :) Keep up the great work my man and let me know if you need anything!

**Comment by SwapFunction** [comment]
Okay, that should be okay for now. Color scheme should be done by this week too. I'll push it later today on the new week. Sorry for the late update. I'll also include the libraries used in the docs.

**Comment by adilanchian** [comment]
Goooood looks, Ab! 

I know you feel slow this week, but don't worry. You are getting so much closer to your goal my dude :)
